stages:
  - build
  - scan
  - sonar

build:
  stage: build
  tags: [self-hosted, test]
  script:
    - pwsh ./release/steps/build.ps1 test

unit-test:
  stage: scan
  tags: [self-hosted, test]
  needs: [build]
  script:
    - pwsh ./release/steps/unit-test.ps1 test

gitleaks:
  stage: scan
  tags: [self-hosted, test]
  needs: [unit-test]
  script:
    - pwsh ./release/steps/gitleaks.ps1 test

semgrep:
  stage: scan
  tags: [self-hosted, test]
  needs: [gitleaks]
  script:
    - pwsh ./release/steps/semgrep.ps1 test

syft:
  stage: scan
  tags: [self-hosted, test]
  needs: [build]
  script:
    - pwsh ./release/steps/syft.ps1 test

grype:
  stage: scan
  tags: [self-hosted, test]
  needs: [syft, semgrep]
  script:
    - pwsh ./release/steps/grype.ps1 test

trivy:
  stage: scan
  tags: [self-hosted, test]
  needs: [grype]
  script:
    - pwsh ./release/steps/trivy.ps1 test

sonar:
  stage: sonar
  tags: [self-hosted, test]
  needs: [trivy]
  script:
    - pwsh ./release/steps/sonar.ps1 test
