stages:
  - build
  - scan
  - sonar
  - deploy

default:
  before_script:
    - apk add --no-cache bash

build:
  stage: build
  tags: [self-hosted, test]
  script:
    - bash ./release/steps/build.sh test

unit-test:
  stage: scan
  image: golang:1.25.11-alpine
  tags: [self-hosted, test]
  needs: [build]
  script:
    - bash ./release/steps/unit-test.sh test

trivy:
  stage: scan
  tags: [self-hosted, test]
  needs: [unit-test]
  script:
    - bash ./release/steps/trivy.sh test

sonar:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:11.5
  tags: [self-hosted, test]
  needs: [unit-test]
  script:
    - bash ./release/steps/sonar.sh test

deploy:
  stage: deploy
  tags: [self-hosted, test]
  needs: [build, trivy, sonar]
  script:
    - bash ./release/steps/deploy.sh test
