#!/usr/bin/env pwsh
$ErrorActionPreference = 'Stop'

. "$PSScriptRoot/lib/Env.ps1"
. "$PSScriptRoot/lib/PostgreSql.ps1"

[void][Env]::new()

if (-not (Test-Path 'assets/db.sql')) { throw '[!] Missing assets/db.sql' }
if (-not (Get-Command psql -ErrorAction SilentlyContinue)) { throw '[!] psql required' }

$pg = [PostgreSql]::new()
$pg.EnsureDatabase()
Write-Host '[+] Applying schema → assets/db.sql'
$pg.ExecFile('assets/db.sql')
Write-Host '[+] Done — db schema'

# SIG # Begin signature block
# MIIHBQYJKoZIhvcNAQcCoIIG9jCCBvICAQMxDTALBglghkgBZQMEAgEwewYKKwYB
# BAGCNwIBBKBtBGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCA/U586xaIf5aKw
# ht3iV7LD+FB/w0790TzyBm3X93fhOKCCA1QwggNQMIIC9qADAgECAhEAn7eSCz3E
# R/b0C5YxX/PjyDAKBggqhkjOPQQDAjAgMR4wHAYDVQQDExVOb3R0SW5mcmEgSW50
# ZXJuYWwgQ0EwHhcNMjYwNzI3MjM0NDE1WhcNMjcwNzI3MjM0NDE1WjAlMSMwIQYD
# VQQDExpOT1RUSU5GUkEgTElNSVRFRCBTT0ZUV0FSRTCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAKRICuzioM/pLsdWW/uV0Hl7Y5FHNBPTEl3X/oGK+BAi
# kC0es0CLXLykWpsJ/f9ldyyHlMzwUR1zEIhCZXEyo+uqQ8B1yWke7rQ4wkWE6/DU
# htCLSiySkf/KB389/ptcEM+jJ48DQGi0+8K6QQ02vEOAQKLfxA4Rrnl5BYY+nnNs
# Rpa+B6K40i/aFAsc60gbG3SGQePzuHHbPl6CE5AzQNY2WBpY77aonZ830RM5AsS4
# Xe7P8cDJ7Gahw6ZjLEriCaR3xBytPy63RiZdW8upuQ0AIFz4/8GVRYuOJ1wGeU53
# b0OZhj/6Z481Zry0VcBvGfHidIVkQKbWZQ2QWdkSBbSAIR92tKpSqSDy4VQYQ4RO
# l3NY/QHkJsAl6EGzQ514P+qUzkSyxgSNHZFCknqTu6gXtemaCUC7z/eLZDibw+mg
# yAuyLTZoeAlDPaHT4FOPfB8pn6UuGb/LwJwFlBHGAkaYlfAkx3BJYIsQpfPwKxfN
# Ufds8LMYArJlFZJnJ1EmJSE+qIu0cN7SyuFDAdGszrVjltYswzAfhE0NRQQm4HiG
# CWG9ZxDD1TxbhvEecgJCOMy/dZCcjEEzq4wZxSVPicn0QowKDWHy1GpgdR3pT+Ok
# zuIBpfEeXW5uW9e0yoOzwOnh1XCRp8hv+B4l4RvTEl3ccZ+PcmAcsLHODqvW4vmT
# AgMBAAGjQTA/MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
# MBaAFKF88Blhy5xs0hQfn4medNFL3FoXMAoGCCqGSM49BAMCA0gAMEUCIQDwlWDa
# ojXZG8h5O2XzW/IG9h+GUKAmx8SCd7NuhB0SUAIgJkQlleqNoGkPuDyi08MuVI36
# ezJPirlP+IxtyaFnz10xggMHMIIDAwIBATA1MCAxHjAcBgNVBAMTFU5vdHRJbmZy
# YSBJbnRlcm5hbCBDQQIRAJ+3kgs9xEf29AuWMV/z48gwCwYJYIZIAWUDBAIBoHww
# EAYKKwYBBAGCNwIBDDECMAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
# KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIG5/LZfW
# yW4YRglofJsCDq0cFUBzikrt3mLAiyrg2RnmMAsGCSqGSIb3DQEBAQSCAgBHE+Td
# OSfnXBkAlX54QGZaV9S61kgx5RXXFkdoSkMKWFKhtHvNeEyC7hHCh9HASB9Kt2XW
# BsCsXZ2Sp81ielUt1YCP6K2DNkZcWyi5IwqCoPb24ZNwBIzULJ1Zmg15jHBgYRjp
# w1nnI8h7WYqpT7Ng+0U3UOkpM/GKaAABNI8LxTD1ruwAN2FUdO6xksUrbwkP2qvW
# qXrlQRMSj0GFZSJhILuSuDAUsti6hZx903kfp3iEJpXQrDmlU+yJGi7Ir2ULC0QN
# /yKAXSvbWSDW2l7F+RMEguxT8zcSds1sykwuo1YDDiq5CZrgod4pxPHLiNBd0R9+
# 9xWa1iYxSZ5XzTDyKSFSx5UJESo1XRhGxZIbaTzUm0aodxTapd5Ox5SJYQtBp1Tf
# i2HEUQTugCAUtkohsx9JhIuMUXZjgY8+PCxIInhg/gNb8+sIGKFf3nllth5ebyhP
# VZGkh9UFzEUJ6QQSsaOcDEmGddVDM3b2ctSHMMU9JV6lq8IgpzKlAloi8y8N4GOM
# hN9cfbDPi31I91eUNCQLZNzsLYt343NDpVsWzCgQNQ4xJvrSBRxJrS/UZ+p59A3g
# E6q4x1zjygvUpj12DeiPj3Q4/7+cd76Wk1/N6NOrpnd/u9KkyMioiBdPnD7t3zlK
# m6bKmkazV75U265AUbm/GPIwEtQB+NHR4iLROqErMCkGDCsGAQQBgoxMCgABAzEZ
# BBdodHRwczovL25vdHRpbmZyYS5jby51aw==
# SIG # End signature block
