name: deploy-live

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/build.ps1 live

  unit-test:
    needs: build
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/unit-test.ps1 live

  gitleaks:
    needs: unit-test
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/gitleaks.ps1 live

  semgrep:
    needs: gitleaks
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/semgrep.ps1 live

  syft:
    needs: build
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/syft.ps1 live

  grype:
    needs: [syft, semgrep]
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/grype.ps1 live

  trivy:
    needs: grype
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/trivy.ps1 live

  sonar:
    needs: trivy
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/sonar.ps1 live

  push:
    needs: sonar
    runs-on: [self-hosted, live, 1imooo]
    steps:
      - uses: actions/checkout@v4
      - run: pwsh ./release/steps/push.ps1 live
